# -*- coding: utf-8 -*-
"""Tracking - ByteTrack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YdeWv2bqstc-gMQehutDrhGm_Hwe2cxL
"""

!pip install ultralytics supervision opencv-python

!wget -O traffic_video.mp4 "https://raw.githubusercontent.com/intel-iot-devkit/sample-videos/master/car-detection.mp4"

import cv2
import numpy as np
from ultralytics import YOLO
import supervision as sv

# 1. Modeli ve video kaynağını hazırlayalım
model = YOLO('yolov8n.pt')
video_path = "traffic_video.mp4"
video_info = sv.VideoInfo.from_video_path(video_path)

# 2. Sanal sayım çizgisini tanımlayalım
start_point = sv.Point(x=50, y=int(video_info.height * 0.75))
end_point = sv.Point(x=video_info.width - 50, y=int(video_info.height * 0.75))
line_zone = sv.LineZone(start=start_point, end=end_point)

# 3. Görselleştirme araçları
box_annotator = sv.BoxAnnotator(thickness=2)
label_annotator = sv.LabelAnnotator(text_scale=0.5, text_thickness=1)
line_zone_annotator = sv.LineZoneAnnotator(thickness=2, text_thickness=1, text_scale=0.8)
byte_tracker = sv.ByteTrack()

# Sadece araç sınıfları (2=car, 3=motorcycle, 5=bus, 7=truck)
TARGET_CLASSES = [2, 3, 5, 7]

# 4. Videoyu kare kare işleme fonksiyonu
def process_frame(frame: np.ndarray, index: int) -> np.ndarray:
    results = model(frame, verbose=False)[0]
    detections = sv.Detections.from_ultralytics(results)

    # Araç olmayanları filtrele
    detections = detections[np.isin(detections.class_id, TARGET_CLASSES)]

    # Nesne takibi (ByteTrack)
    detections = byte_tracker.update_with_detections(detections)

    # Çizgiden geçenleri tetikle
    line_zone.trigger(detections=detections)

    # Ekrana çizimler (Güncel Supervision parametreleri)
    labels = [f"#{tracker_id} {model.names[class_id]}"
              for tracker_id, class_id in zip(detections.tracker_id, detections.class_id)]

    annotated_frame = box_annotator.annotate(scene=frame.copy(), detections=detections)
    annotated_frame = label_annotator.annotate(scene=annotated_frame, detections=detections, labels=labels)
    # Güncellenen kısım: 'scene' yerine doğrudan ilk argüman olarak 'annotated_frame' veriyoruz
    annotated_frame = line_zone_annotator.annotate(annotated_frame, line_counter=line_zone)

    return annotated_frame

# 5. Videoyu işle ve kaydet
print("Video işleniyor, lütfen bekleyin...")
sv.process_video(
    source_path=video_path,
    target_path="cikis_video.mp4",
    callback=process_frame
)

print(f"\nİşlem Tamamlandı!")
print(f"Giriş Yapan Araç Sayısı (In): {line_zone.in_count}")
print(f"Çıkış Yapan Araç Sayısı (Out): {line_zone.out_count}")

import cv2
import numpy as np
from ultralytics import YOLO
import supervision as sv

# 1. Model ve video hazırlığı
model = YOLO('yolov8n.pt')
video_path = "traffic_video.mp4"
video_info = sv.VideoInfo.from_video_path(video_path)

# 2. Çizgiyi yolun tam ortasına (y = height * 0.50) konumlandırıyoruz
start_point = sv.Point(x=10, y=int(video_info.height * 0.50))
end_point = sv.Point(x=video_info.width - 10, y=int(video_info.height * 0.50))
line_zone = sv.LineZone(start=start_point, end=end_point)

# 3. Anotasyon ve takip araçları
box_annotator = sv.BoxAnnotator(thickness=2)
label_annotator = sv.LabelAnnotator(text_scale=0.5, text_thickness=1)
line_zone_annotator = sv.LineZoneAnnotator(thickness=2, text_thickness=1, text_scale=0.8)
byte_tracker = sv.ByteTrack()

TARGET_CLASSES = [2, 3, 5, 7]  # car, motorcycle, bus, truck

def process_frame(frame: np.ndarray, index: int) -> np.ndarray:
    results = model(frame, verbose=False)[0]
    detections = sv.Detections.from_ultralytics(results)

    # Araçları filtrele
    detections = detections[np.isin(detections.class_id, TARGET_CLASSES)]

    # Takip kimliği ata (ByteTrack)
    detections = byte_tracker.update_with_detections(detections)

    # Çizgi kesişimini tetikle
    line_zone.trigger(detections=detections)

    labels = [f"#{tracker_id} {model.names[class_id]}"
              for tracker_id, class_id in zip(detections.tracker_id, detections.class_id)]

    annotated_frame = box_annotator.annotate(scene=frame.copy(), detections=detections)
    annotated_frame = label_annotator.annotate(scene=annotated_frame, detections=detections, labels=labels)
    annotated_frame = line_zone_annotator.annotate(annotated_frame, line_counter=line_zone)

    return annotated_frame

print("Video yeniden işleniyor...")
sv.process_video(
    source_path=video_path,
    target_path="cikis_video.mp4",
    callback=process_frame
)

print(f"\nİşlem Tamamlandı!")
print(f"Giriş Yapan Araç Sayısı (In): {line_zone.in_count}")
print(f"Çıkış Yapan Araç Sayısı (Out): {line_zone.out_count}")

import cv2
import matplotlib.pyplot as plt

# Videodan ilk kareyi okuyup modelle çizgi pozisyonunu görselleştirelim
cap = cv2.VideoCapture("traffic_video.mp4")
ret, frame = cap.read()
cap.release()

if ret:
    results = model(frame, verbose=False)[0]
    detections = sv.Detections.from_ultralytics(results)
    detections = detections[np.isin(detections.class_id, TARGET_CLASSES)]

    # Kutuları ve çizgiyi çiz
    annotated = box_annotator.annotate(scene=frame.copy(), detections=detections)
    annotated = line_zone_annotator.annotate(annotated, line_counter=line_zone)

    annotated_rgb = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(10, 6))
    plt.imshow(annotated_rgb)
    plt.axis('off')
    plt.title(f"Video Boyutu: {video_info.width}x{video_info.height}")
    plt.show()
else:
    print("Video karesi okunamadı!")

!wget -O traffic_highway.mp4 "https://github.com/intel-iot-devkit/sample-videos/raw/master/people-detection.mp4"

import cv2
import numpy as np
from ultralytics import YOLO
import supervision as sv

model = YOLO('yolov8n.pt')
video_path = "traffic_highway.mp4"
video_info = sv.VideoInfo.from_video_path(video_path)

# Çizgiyi ekranın ortasına koyuyoruz
start_point = sv.Point(x=10, y=int(video_info.height * 0.6))
end_point = sv.Point(x=video_info.width - 10, y=int(video_info.height * 0.6))
line_zone = sv.LineZone(start=start_point, end=end_point)

box_annotator = sv.BoxAnnotator(thickness=2)
label_annotator = sv.LabelAnnotator(text_scale=0.5, text_thickness=1)
line_zone_annotator = sv.LineZoneAnnotator(thickness=2, text_thickness=1, text_scale=0.8)
byte_tracker = sv.ByteTrack()

# COCO: 0=person, 2=car, 3=motorcycle, 5=bus, 7=truck
TARGET_CLASSES = [0, 2, 3, 5, 7]

def process_frame(frame: np.ndarray, index: int) -> np.ndarray:
    results = model(frame, verbose=False)[0]
    detections = sv.Detections.from_ultralytics(results)

    # İlgili sınıfları filtrele
    detections = detections[np.isin(detections.class_id, TARGET_CLASSES)]

    # Takip kimliği ata
    detections = byte_tracker.update_with_detections(detections)

    # Çizgi tetikleme
    line_zone.trigger(detections=detections)

    labels = [f"#{tracker_id} {model.names[class_id]}"
              for tracker_id, class_id in zip(detections.tracker_id, detections.class_id)]

    annotated_frame = box_annotator.annotate(scene=frame.copy(), detections=detections)
    annotated_frame = label_annotator.annotate(scene=annotated_frame, detections=detections, labels=labels)
    annotated_frame = line_zone_annotator.annotate(annotated_frame, line_counter=line_zone)

    return annotated_frame

print("Video işleniyor...")
sv.process_video(
    source_path=video_path,
    target_path="sayim_cikti.mp4",
    callback=process_frame
)

print(f"\nİşlem Tamamlandı!")
print(f"Giriş Yapanlar (In): {line_zone.in_count}")
print(f"Çıkış Yapanlar (Out): {line_zone.out_count}")

import cv2
import numpy as np

# 100 karelik, 640x480 boyutunda sentetik bir otoyol videosu oluşturalım
width, height = 640, 480
fps = 20
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('traffic_sim.mp4', fourcc, fps, (width, height))

# 3 farklı aracın yukarıdan aşağıya doğru hareketini çizelim
for frame_idx in range(100):
    frame = np.full((height, width, 3), 40, dtype=np.uint8)  # Asfalt zemin

    # Şerit çizgileri
    cv2.line(frame, (width // 2, 0), (width // 2, height), (255, 255, 255), 2)

    # 1. Araç (Sol şerit)
    y1 = int(frame_idx * 5)
    if y1 < height:
        cv2.rectangle(frame, (200, y1), (280, y1 + 100), (0, 0, 255), -1)  # Kırmızı araç

    # 2. Araç (Sağ şerit, biraz geriden gelen)
    y2 = int((frame_idx - 25) * 6)
    if 0 <= y2 < height:
        cv2.rectangle(frame, (360, y2), (440, y2 + 110), (255, 100, 0), -1)  # Mavi araç

    out.write(frame)

out.release()
print("Sentetik test videosu (traffic_sim.mp4) hazır!")

import cv2
import numpy as np
from ultralytics import YOLO
import supervision as sv

# 1. Model ve video hazırlığı
model = YOLO('yolov8n.pt')
video_path = "car_test.mp4"
video_info = sv.VideoInfo.from_video_path(video_path)

# 2. Araçlar sağdan sola aktığı için DİKEY bir sayım çizgisi kuruyoruz
# x koordinatı ekranın tam ortasında (width * 0.5), y koordinatı yukarıdan aşağıya uzanıyor
start_point = sv.Point(x=int(video_info.width * 0.5), y=10)
end_point = sv.Point(x=int(video_info.width * 0.5), y=video_info.height - 10)
line_zone = sv.LineZone(start=start_point, end=end_point)

# 3. Anotasyon ve takip araçları (Argümansız varsayılan ByteTrack)
box_annotator = sv.BoxAnnotator(thickness=2)
label_annotator = sv.LabelAnnotator(text_scale=0.5, text_thickness=1)
line_zone_annotator = sv.LineZoneAnnotator(thickness=2, text_thickness=1, text_scale=0.8)
byte_tracker = sv.ByteTrack()

# Sadece araç sınıfları: car (2), motorcycle (3), bus (5), truck (7)
TARGET_CLASSES = [2, 3, 5, 7]

def process_frame(frame: np.ndarray, index: int) -> np.ndarray:
    results = model(frame, verbose=False, conf=0.3)[0]
    detections = sv.Detections.from_ultralytics(results)

    # Araçları filtrele
    detections = detections[np.isin(detections.class_id, TARGET_CLASSES)]

    # Takip kimliği ata
    detections = byte_tracker.update_with_detections(detections)

    # Dikey çizgiden geçişi tetikle
    line_zone.trigger(detections=detections)

    labels = []
    if len(detections) > 0 and detections.tracker_id is not None:
        labels = [f"#{tid} {model.names[cid]}"
                  for tid, cid in zip(detections.tracker_id, detections.class_id)]

    annotated = box_annotator.annotate(scene=frame.copy(), detections=detections)
    if labels:
        annotated = label_annotator.annotate(scene=annotated, detections=detections, labels=labels)
    annotated = line_zone_annotator.annotate(annotated, line_counter=line_zone)

    return annotated

print("Video dikey çizgi ile işleniyor...")
sv.process_video(source_path=video_path, target_path="sayim_sonuc.mp4", callback=process_frame)

print(f"\nİşlem Tamamlandı!")
print(f"Giriş (In): {line_zone.in_count}")
print(f"Çıkış (Out): {line_zone.out_count}")

import cv2
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
cap = cv2.VideoCapture("car_test.mp4")

detected_classes = set()
total_frames = 0
total_boxes = 0

while cap.isOpened() and total_frames < 100:
    ret, frame = cap.read()
    if not ret:
        break
    total_frames += 1
    results = model(frame, verbose=False, conf=0.15)[0]
    boxes = results.boxes
    if len(boxes) > 0:
        total_boxes += len(boxes)
        for c in boxes.cls:
            detected_classes.add(model.names[int(c)])

cap.release()

print(f"Taranan Kare: {total_frames}")
print(f"Toplam Tespit Edilen Kutu: {total_boxes}")
print(f"Tespit Edilen Nesne Türleri: {detected_classes}")

import cv2
import numpy as np
from ultralytics import YOLO
import supervision as sv

model = YOLO('yolov8n.pt')
video_path = "car_test.mp4"
video_info = sv.VideoInfo.from_video_path(video_path)

# Dikey çizgimiz (x ekseninde ekranın ortası)
line_x = int(video_info.width * 0.5)

box_annotator = sv.BoxAnnotator(thickness=2)
label_annotator = sv.LabelAnnotator(text_scale=0.5, text_thickness=1)
byte_tracker = sv.ByteTrack()

# Takip mantığı için hafıza:
# Her ID'nin önceki x koordinatını ve sayılan ID'leri tutuyoruz
previous_x_positions = {}
counted_ids = set()
in_count = 0
out_count = 0

TARGET_CLASSES = [2, 3, 5, 7, 6]  # car, motorcycle, bus, truck, train

def process_frame(frame: np.ndarray, index: int) -> np.ndarray:
    global in_count, out_count

    results = model(frame, verbose=False, conf=0.2)[0]
    detections = sv.Detections.from_ultralytics(results)
    detections = detections[np.isin(detections.class_id, TARGET_CLASSES)]
    detections = byte_tracker.update_with_detections(detections)

    labels = []
    if len(detections) > 0 and detections.tracker_id is not None:
        for xyxy, tracker_id, class_id in zip(detections.xyxy, detections.tracker_id, detections.class_id):
            labels.append(f"#{tracker_id} {model.names[class_id]}")

            # Kutunun merkez x noktası
            center_x = (xyxy[0] + xyxy[2]) / 2

            # Önceki koordinat varsa çizgi geçiş kontrolü yap
            if tracker_id in previous_x_positions:
                prev_x = previous_x_positions[tracker_id]

                if tracker_id not in counted_ids:
                    # Soldan sağa geçiş
                    if prev_x < line_x and center_x >= line_x:
                        in_count += 1
                        counted_ids.add(tracker_id)
                    # Sağdan sola geçiş
                    elif prev_x > line_x and center_x <= line_x:
                        out_count += 1
                        counted_ids.add(tracker_id)

            previous_x_positions[tracker_id] = center_x

    annotated = box_annotator.annotate(scene=frame.copy(), detections=detections)
    if labels:
        annotated = label_annotator.annotate(scene=annotated, detections=detections, labels=labels)

    # Çizgiyi ve sayacı görsel olarak ekrana çiziyoruz
    cv2.line(annotated, (line_x, 0), (line_x, video_info.height), (0, 0, 255), 2)
    cv2.putText(annotated, f"In: {in_count} | Out: {out_count}", (30, 50),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

    return annotated

print("Kendi çizgi takip algoritmamızla video işleniyor...")
sv.process_video(source_path=video_path, target_path="sayim_kesin_sonuc.mp4", callback=process_frame)

print(f"\nİşlem Tamamlandı!")
print(f"Toplam Giriş (In): {in_count}")
print(f"Toplam Çıkış (Out): {out_count}")
print(f"Toplam Tekil Sayılan Araç: {len(counted_ids)}")